# Generated by Django 4.1.3 on 2022-11-13 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildevice',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='destination.area'),
        ),
        migrations.AddField(
            model_name='waterdevice',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='destination.area'),
        ),
    ]
